query messages($limit: Int, $offset: Int) {
  messages(limit: $limit, offset: $offset, order_by: { id: desc }) {
    id
    title
    body
    url
    imageUrl
    publishedAt
    message_tags {
      tag {
        name
      }
    }
  }
  messages_aggregate {
    aggregate {
      count
    }
  }
}
